[custom]
;===========设置规则标志位=============
ruleset=选择,https://raw.githubusercontent.com/912b/clash/main/rules/dns.list
ruleset=直连,https://raw.githubusercontent.com/912b/clash/main/rules/Download.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Apple.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AppleNews.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AppleTV.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/WeChat/WeChat.list
ruleset=直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Tencent/Tencent.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Alibaba.list
ruleset=教育,https://raw.githubusercontent.com/912b/clash/main/rules/edu.list
ruleset=通讯,https://raw.githubusercontent.com/912b/clash/main/rules/zoom.list
ruleset=通讯,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Discord/Discord.list
ruleset=通讯,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Line.list
ruleset=微软,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=微软,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=微软,https://raw.githubusercontent.com/912b/clash/main/rules/Xbox.list
ruleset=游戏,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=游戏,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/UBI/UBI.list
ruleset=游戏,https://raw.githubusercontent.com/912B/clash/main/rules/switch.list
ruleset=选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Facebook.list
ruleset=选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list
ruleset=选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleEarth.list
ruleset=选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GoogleFCM/GoogleFCM.list
ruleset=选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list
ruleset=选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Reddit.list
ruleset=选择,https://raw.githubusercontent.com/912B/clash/main/rules/Telegram.list
ruleset=选择,https://raw.githubusercontent.com/912b/clash/main/rules/tw.list
ruleset=选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitter.list
ruleset=选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Wikipedia.list
ruleset=选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube.list
ruleset=直连,[]GEOIP,CN
ruleset=其他,[]FINAL



;==========设置分组标志位===============
custom_proxy_group=选择`select`[]测速`[]故障转移`.*
custom_proxy_group=教育`select`[]选择`[]测速`[]故障转移`[]DIRECT`.*
custom_proxy_group=通讯`select`[]测速`[]故障转移`[]DIRECT`.*
custom_proxy_group=游戏`select`[]选择`(^(?!.*(Lv3)).*)`[]DIRECT
custom_proxy_group=微软`select`[]选择`(^(?!.*(Lv3)).*)`[]DIRECT
custom_proxy_group=其他`select`[]故障转移`[]测速`[]DIRECT
custom_proxy_group=测速`url-test`(Lv3)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=故障转移`fallback`.*`http://www.gstatic.com/generate_204`300,,50
#custom_proxy_group=2倍`url-test`(2.0)`http://www.gstatic.com/generate_204`300,,50
#custom_proxy_group=3倍`url-test`(3.0|IPLC)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=直连`select`[]DIRECT
#custom_proxy_group=节点选择`select`(^(?!.*(美国|日本)).*)  # 表示创建一个叫 节点选择 的 select 策略组,并向其中**依次**添加名字不包含'美国'或'日本'的节点
#custom_proxy_group=香港节点`select`(^(?!.*?(3.0)).*(港|HK|Hong Kong) )  #不包含3.0 包含港的节点
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

